server:
  port: 9900
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8
    username: root
    password: passw0rd
    driver: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: -1
    timeout: 0
logging:
  level:
    com.seebon.delivery.dao: DEBUG

mybatis:
  type-aliases-package: com.ufi.pdioms.resource.rest.*  #这个是扫描实体对象的
  mapper-locations:  classpath:mapper/*.xml,classpath:mapper/*/*.xml,classpath:mapper/*/*/*.xml
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
